@startuml
Operario "1" <--"*" ParteMO
Tarea "1" <.. "*" ParteMO
ParteMO "*" --> "1" Estado
ParteMO "*" --> "1" Proyecto
Tarea "*" <-- "1" Proyecto
Proyecto "*" --> "1" Estado
Proyecto "*"--> "1" Empresa
ParteMO "1" --> "*" LogValidacionParteMO
Estado "1" <-- "*" LogValidacionParteMO
ValidacionParteMO "1" <-- "*" LogValidacionParteMO
ValidacionParteMO "*" --> "1" Tipo

class Operario{
  -int legajo
  -String nombre
  -String categoria
}
class Tarea{
  -String codigo
  -String descripcion
}
class ParteMO{
  -Date fecha
  -Time horaDesde
  -Time horaHasta
  -Float horas
}
class Proyecto{
  -String codigo
  -String descripcion
}
class Empresa{
  -String nombre
  -String cuit
  -String observaciones
}
class Estado{
  -String nombre
  -String descripcion
}
class LogValidacionParteMO{
  -Date fecha
}
class ValidacionParteMO{
  -String nombre
  -String descripcion
  -String observaciones
  -String validador
}
class Tipo<<Enumeration>>{
  -"Mensaje"
  -"Advertencia"
  -"Error"
  -"Error Grave"
}
@enduml
